import { MathPageMeta } from '../types';

export const mathTools: MathPageMeta[] = [
  {
    id: "linear-solver",
    title: "Linear Equation Solver",
    description: "Solve linear equations step-by-step and visualize the solution process",
    category: "Algebra",
    level: "Beginner",
    icon: "⚙️",
    color: "from-blue-600 to-indigo-700",
    shape: "parallelogram",
    enabled: true,
    featured: true,
    tags: ["algebra", "equations", "solver", "linear", "step-by-step"],
    keywords: ["linear equations", "solver", "algebra", "mathematics", "step-by-step"],
    relatedTools: ["linear-systems", "polynomial"],
    path: "/math/linear-solver"
  },
  {
    id: "polynomial",
    title: "Polynomial Factorization",
    description: "Factor polynomials into their simplest form with interactive visualizations",
    category: "Algebra",
    level: "Intermediate",
    icon: "🧩",
    color: "from-purple-600 to-indigo-700",
    shape: "hexagon",
    enabled: true,
    featured: true,
    tags: ["algebra", "polynomials", "factoring", "mathematics", "visualization"],
    keywords: ["polynomial", "factorization", "algebra", "mathematics", "interactive"],
    relatedTools: ["linear-solver", "quadratic"],
    path: "/math/polynomial"
  },
  {
    id: "linear-systems",
    title: "Linear Systems Solver",
    description: "Solve systems of linear equations step-by-step using elimination, substitution, or matrix methods. Visualize the solution process with interactive steps and graphical representation.",
    category: "Algebra",
    level: "Intermediate",
    icon: "🔢",
    color: "from-indigo-600 to-blue-700",
    shape: "rectangle",
    enabled: true,
    featured: true,
    tags: ["algebra", "linear systems", "matrices", "equations", "visualization"],
    keywords: ["linear systems", "matrices", "algebra", "solver", "interactive"],
    relatedTools: ["linear-solver", "matrix-calculator"],
    path: "/math/linear-systems"
  },
  {
    id: "pythagoras",
    title: "Pythagorean Theorem Calculator",
    description: "Calculate the sides of a right triangle using the Pythagorean theorem",
    category: "Geometry",
    level: "Beginner",
    icon: "📐",
    color: "from-sky-600 to-cyan-700",
    shape: "triangle",
    enabled: true,
    featured: true,
    tags: ["geometry", "pythagorean theorem", "triangles", "right triangles", "calculator"],
    keywords: ["pythagorean", "theorem", "geometry", "triangles", "calculator"],
    relatedTools: ["geometry-angle", "geometry-trigonometry"],
    path: "/math/pythagoras"
  },
  
  // Advanced Mathematics tools
  {
    id: "collatz",
    title: "Collatz Conjecture Explorer",
    description: "Explore the famous Collatz Conjecture (3n+1 problem) with visualizations and interactive sequences",
    category: "Number Theory",
    level: "Intermediate",
    icon: "3n+1",
    color: "from-red-900 to-orange-700",
    shape: "hexagon",
    enabled: true,
    featured: true,
    tags: ["number theory", "collatz conjecture", "sequences", "3n+1 problem", "unsolved problems"],
    keywords: ["collatz", "3n+1", "sequence", "hailstone", "conjecture"],
    relatedTools: ["riemann", "p-adic"],
    path: "/math/collatz"
  },
  {
    id: "riemann",
    title: "Riemann Hypothesis Explorer",
    description: "Explore the fascinating Riemann Hypothesis and its connections to prime numbers, with interactive visualizations and explanations",
    category: "Number Theory",
    level: "Advanced",
    icon: "ζ",
    color: "from-purple-900 to-indigo-700",
    shape: "rectangle",
    enabled: true,
    featured: true,
    tags: ["number theory", "riemann hypothesis", "prime numbers", "zeta function", "complex analysis"],
    keywords: ["riemann", "zeta", "prime numbers", "critical line", "non-trivial zeros"],
    relatedTools: ["collatz", "p-adic"],
    path: "/math/riemann"
  },
  {
    id: "p-adic",
    title: "P-adic Number Explorer",
    description: "Explore the fascinating world of p-adic numbers and their applications in number theory and mathematical analysis",
    category: "Number Theory",
    level: "Advanced",
    icon: "|·|p",
    color: "from-teal-900 to-green-700",
    shape: "circle",
    enabled: true,
    featured: true,
    tags: ["number theory", "p-adic numbers", "analysis", "algebra", "non-Archimedean"],
    keywords: ["p-adic", "ultrametric", "valuation", "number theory", "analysis"],
    relatedTools: ["riemann", "collatz"],
    path: "/math/p-adic"
  },
  
  // Calculus tools
  {
    id: "derivative-calculator",
    title: "Derivative Calculator",
    description: "Calculate derivatives of functions with step-by-step solutions and visualizations",
    category: "Calculus",
    level: "Intermediate",
    icon: "📉",
    color: "from-blue-600 to-indigo-600",
    shape: "rectangle",
    enabled: true,
    featured: true,
    tags: ["calculus", "derivatives", "differentiation", "functions", "math"],
    keywords: ["differentiate", "derivative", "function", "calculus", "rate of change"],
    relatedTools: ["integral-calculator", "limit-calculator"],
    path: "/math/calculus/derivative-calculator"
  },
  {
    id: "integral-calculator",
    title: "Integral Calculator",
    description: "Calculate indefinite and definite integrals with step-by-step solutions and visualizations",
    category: "Calculus",
    level: "Intermediate",
    icon: "∫",
    color: "from-green-600 to-teal-600",
    shape: "rectangle",
    enabled: true,
    featured: true,
    tags: ["calculus", "integration", "integrals", "functions", "antiderivative"],
    keywords: ["integrate", "integral", "antiderivative", "calculus", "area under curve"],
    relatedTools: ["derivative-calculator", "limit-calculator"],
    path: "/math/calculus/integral-calculator"
  },
  {
    id: "limit-calculator",
    title: "Limit Calculator",
    description: "Calculate limits of functions with step-by-step solutions and graphical visualization",
    category: "Calculus",
    level: "Intermediate",
    icon: "→",
    color: "from-amber-600 to-orange-600",
    shape: "rectangle",
    enabled: true,
    featured: true,
    tags: ["calculus", "limits", "functions", "continuity", "infinity"],
    keywords: ["limit", "approach", "infinity", "function", "continuity"],
    relatedTools: ["derivative-calculator", "integral-calculator"],
    path: "/math/calculus/limit-calculator"
  },
  
  // Probability & Statistics tools
  {
    id: "probability-calculator",
    title: "Probability Calculator",
    description: "Calculate probability for common scenarios with step-by-step solutions",
    category: "Probability",
    level: "Beginner",
    icon: "🎲",
    color: "from-green-600 to-blue-700",
    shape: "circle",
    enabled: true,
    featured: true,
    tags: ["probability", "statistics", "combinations", "permutations", "odds"],
    keywords: ["chance", "likelihood", "odds", "probability calculator"],
    relatedTools: ["statistics-analyzer"],
    path: "/math/probability/probability-calculator"
  },
  {
    id: "data-analysis",
    title: "Data Analysis Tool",
    description: "Analyze datasets with descriptive statistics, visualizations, and hypothesis testing",
    category: "Statistics",
    level: "Intermediate",
    icon: "📊",
    color: "from-blue-600 to-indigo-600",
    shape: "rectangle",
    enabled: true,
    featured: true,
    tags: ["statistics", "data analysis", "datasets", "visualization", "hypothesis testing"],
    keywords: ["analyze", "data", "statistics", "dataset", "visualization"],
    relatedTools: ["statistics-analyzer", "regression-analysis"],
    path: "/math/statistics/data-analysis"
  },
  
  // Geometry tools
  {
    id: "area-calculator",
    title: "Area Calculator",
    description: "Calculate the area of various 2D shapes with interactive visualizations",
    category: "Geometry",
    level: "Beginner",
    icon: "◻️",
    color: "from-blue-500 to-indigo-500",
    shape: "square",
    enabled: true,
    featured: true,
    tags: ["geometry", "area", "shapes", "measurement", "calculation"],
    keywords: ["area", "square", "rectangle", "triangle", "circle", "polygon"],
    relatedTools: ["pythagoras"],
    path: "/math/geometry/area-calculator"
  },
  {
    id: "pythagorean-calculator",
    title: "Pythagorean Theorem Calculator",
    description: "Calculate the sides of a right triangle using the Pythagorean theorem with interactive visualizations",
    category: "Geometry",
    level: "Beginner",
    icon: "📐",
    color: "from-sky-600 to-cyan-700",
    shape: "triangle",
    enabled: true,
    featured: true,
    tags: ["geometry", "pythagorean theorem", "triangles", "right triangles", "calculator"],
    keywords: ["pythagorean", "theorem", "geometry", "triangles", "hypotenuse", "right angle"],
    relatedTools: ["area-calculator"],
    path: "/math/pythagorean-calculator"
  }
]; 